# Generated by Django 2.0.5 on 2018-05-16 15:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPANXX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npa', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)])),
                ('nxx', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)])),
                ('manual_entry', models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='NPANXXThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_entry', models.BooleanField(default=False, editable=False)),
                ('npanxx_dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_set', to='prefix.NPANXX')),
                ('npanxx_src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_set', to='prefix.NPANXX')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='npanxx',
            name='local_to',
            field=models.ManyToManyField(through='prefix.NPANXXThrough', to='prefix.NPANXX'),
        ),
        migrations.AddField(
            model_name='npanxx',
            name='region',
            field=models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.PROTECT, to='prefix.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='npanxx',
            unique_together={('npa', 'nxx')},
        ),
    ]
