# Generated by Django 2.0.5 on 2018-05-16 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prefix', '0002_auto_20180516_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npanxx',
            options={'verbose_name': 'NPANXX', 'verbose_name_plural': 'NPANXXes'},
        ),
        migrations.AddField(
            model_name='npanxx',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='npanxx',
            name='npa',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)], verbose_name='NPA'),
        ),
        migrations.AlterField(
            model_name='npanxx',
            name='nxx',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(999)], verbose_name='NXX'),
        ),
    ]
