# Generated by Django 2.0.5 on 2018-05-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prefix', '0003_auto_20180516_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NPANXXThrough',
            new_name='NPANXXIsLocal',
        ),
    ]
